version: 2.1
jobs:
  linter:
    machine: true
    steps:
      - checkout
      - run:
          name: Execute pre-commit on Terraform code
          command: docker run -v $PWD:/pre-commit --rm guivin/pre-commit-terraform
workflows:
  build:
    jobs:
      - linter
